</div>
</div>
        <script type="text/javascript">
    $(document).ready(function () {
        $("#menuId_4").addClass("actived");
        var expertsActived = $('#listCaliTrainer .expertsActived');
        if (expertsActived) {
            setTimeout(function () {
                $('#listCaliTrainer').scrollTop(expertsActived.parent().index() * expertsActived.outerHeight(true));
            }, 0);
        }
    });
    </script>
</div>
<div class="box-bottom">
   <div class="webContent">
        <div class="navBottom">
            <ul>
                <li>
                    <a id="menuId_20" href="http://cfycnew.song.com/vn/career">Tuyển dụng</a>
                </li>
                <li>
                    <a id="menuId_21" href="http://cfycnew.song.com/vn/contact">Liên hệ</a>
                </li>
                <li>
                    <a id="menuId_22" href="http://cfycnew.song.com/vn/executive-team">Thông tin</a>
                </li>
                <li>
                    <a id="menuId_23" href="http://cfycnew.song.com/vn/gallery">Hình ảnh</a>
                </li>
                <li>
                    <a id="menuId_24" href="http://cfycnew.song.com/vn/terms-and-conditions">Điều kiện sử dụng</a>
                </li>
                <li>
                    <a id="menuId_25" href="http://cfycnew.song.com/vn/privacy-policy">Chính sách bảo mật</a>
                </li>
                <li>
                    <div class="tabSearch">
                        <form action="http://cfycnew.song.com/vn/search" method="post">
                            <input type="text" class="txtSearch" name="txtKeyword" placeholder="Tìm kiếm">
                            <input type="image" alt="Search" src="images_server/style/images/btnSearch.jpg" class="button-search" name="btSearch">
                        </form>
                    </div>
                </li>
            </ul>
            <div class="btnGotoTop">Lên đầu</div>
        </div>
        <div class="copyright">
            <span>Copyright &copy; 2012 <strong>California Fitness &amp; Yoga</strong> / All rights reserved / Site by <a href="http://www.newenergywave.com"><strong>www.newenergywave.com</strong></a></span>        </div>
        <div class="iconSocial">
            <a href="http://www.facebook.com/cfycvn" target="_blank" class="social6 no-border"><span>&nbsp;</span></a>
            <a href="https://plus.google.com/105335255808989803709/posts" target="_blank" class="social5"><span>&nbsp;</span></a>
            <a href="http://www.twitter.com/cfycvn" target="_blank" class="social2"><span>&nbsp;</span></a>
            <a href="http://www.youtube.com/user/califitnessyogavn" target="_blank" class="social3"><span>&nbsp;</span></a>
            <a href="http://localhost/cfyccenturyon" target="_blank" class="social4"><span>&nbsp;</span></a>
        </div>
    </div>
</div></body></html>