<!doctype html>
<!--[if IE]><![endif]-->
<!--[if lt IE 7 ]> <html lang="vn" class="ie6">    <![endif]-->
<!--[if IE 7 ]>    <html lang="vn" class="ie7">    <![endif]-->
<!--[if IE 8 ]>    <html lang="vn" class="ie8">    <![endif]-->
<!--[if IE 9 ]>    <html lang="vn" class="ie9">    <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html lang="vn"><!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<base href="/CfycDesigner/template/cfycnew/try-a-class/" target="_blank">
<!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" /><![endif]-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Group Fitness tại Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam" />
<meta name="keywords" content="Group Fitness tại Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam"/>
<link rel="canonical" href="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-pa4lg2la1ca2.html" />
<meta property="og:title" content="Group Fitness tại Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam" />
<meta property="og:type" content="article" />
<meta property="og:url" content="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-pa4lg2la1ca2.html" />
<meta property="og:image" content="images_server/phn_image/california-image.jpg" /><meta property="og:site_name" content="California Fitness and Yoga Center" />
<meta property="og:description" content="Group Fitness tại Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam" />
<meta property="fb:app_id" content="460384730738451" />
<title>Group Fitness tại Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam</title>
<link href="images_server/style/bootstrap.min.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<link href="images_server/phn_plugin/jquery-modal/jquery.modal.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<link href="images_server/phn_plugin/page/pace.min.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<link href="images_server/style/home.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<link href="images_server/style/tmp.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<link href="images_server/style/default/cta.css?version=1" rel="stylesheet" type="text/css" media="screen" />
<script type="text/javascript" src="images_server/phn_js/jquery.tools.min.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_js/bootstrap.min.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_js/jquery.lazyload.min.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_js/jcarousellite_1.0.1.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_plugin/page/pace.min.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_js/jsPage.js?version=1"></script>
<script type="text/javascript" src="images_server/phn_plugin/jquery-modal/jquery.modal.min.js?version=1"></script>
<script src="images_server/phn_js/jquery.nicescroll.js?version=1"></script>
</head><body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function () {
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41328653-1', 'cfyc.com.vn');
  ga('send', 'pageview');

</script>
<script>
</script><div>
    <div id="web-mainmenu">
    <div class="webContent">
        <div class="menuTab">
            <div class="menuTopR">
                <ul class="nav" id="nav1">
                                        <li>
                        <div class="blockMenuTop">
                            <a href="/vn" id="menuId_13"> <span>Trang chủ</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/nguoi-noi-tieng-tai-cali-pa5lg2ca11.html" id="menuId_15"> <span>Testimonials</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/cau-lac-bo-tai-ho-chi-minh-pa3lo1lg2.html" id="menuId_3"> <span>Câu lạc bộ</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/gioi-thieu.html" id="menuId_6"> <span>Về chúng tôi</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/group-fitness-pa4lg2la1.html" id="menuId_4"> <span>Dịch vụ</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/thong-tin-the-duc-va-yoga-pa5lg2ca1la21.html" id="menuId_5"> <span>Phong cách sống</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/vn/member" id="menuId_7"> <span>Thành viên</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/vn/schedule" id="menuId_8"> <span>Lịch học</span></a>
                        </div>
                    </li>
                                            <li>
                        <div class="blockMenuTop">
                            <a href="/danh-cho-vip.html" id="menuId_16"> <span>Dành cho Vip</span></a>
                        </div>
                    </li>
                                        </ul>
                <div class="clear"></div>
            </div>
        </div>
        <div class="logoTop">
                        <a href="/CfycDesigner/template/cfycnew/try-a-class/vn">
            <img src="images_server/style/images/LogoCalifornia.png" alt="LogoCalifornia.png" />
            </a>
        </div>
        <div class="clearfix"></div>
        <div class="iconSocial">
            <a href="http://www.facebook.com/cfycvn" target="_blank" class="social6"><span>&nbsp;</span></a>
            <a href="https://plus.google.com/105335255808989803709/posts" target="_blank" class="social5"><span>&nbsp;</span></a>
            <a href="http://www.twitter.com/cfycvn" target="_blank" class="social2"><span>&nbsp;</span></a>
            <a href="http://www.youtube.com/user/califitnessyogavn" target="_blank" class="social3"><span>&nbsp;</span></a>
            <a href="http://localhost/cfyccenturyon" target="_blank" class="social4"><span>&nbsp;</span></a>
        </div>
        <div class="languageTop">
            <a href="group-fitness-pa4lg1la1ca2.html"><img src="images_server/style/images/vn.png" alt="vn.png" height="20"/></a>
        </div>
        <div class="iconCart">
                        <a href="/CfycDesigner/template/cfycnew/try-a-class/mua-hang-pa14lg2.html"><img src="images_server/style/images/CART.png" alt="CART.png" height="20"/></a>
        </div>
    </div>
</div>        <div class="boxTitlePage">
    <div class="webContent">
        <h2 class="TitlePage">
                        Dịch vụ            <span></span>
                    </h2>
    </div>
</div>    <div class="boxLocation">
    <div class="webContent">
        <ul id="boxMenuClubs">
                            <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-pa4lg2la1.html" class="actived">Group Fitness</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/giam-cang-co-pa4lg2la11.html" class="">Giảm căng cơ</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/dance-pa4lg2la2.html" class="">Dance</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/yoga-pa4lg2la3.html" class="">Yoga</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/huan-luyen-ca-nhan-pa4lg2la7.html" class="">Huấn luyện cá nhân</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/kickfit-pa4lg2la5.html" class="">Kickfit</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/vo-tu-do-mma-pa4lg2la10.html" class="">Võ tự do MMA</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/spa-pa4lg2la9.html" class="">Spa</a>
                </li>
                                <li>
                    <a href="/CfycDesigner/template/cfycnew/try-a-class/clb-danh-cho-tre-em-pa4lg2la8.html" class="">Clb dành cho trẻ em</a>
                </li>
                        </ul>
        <div class="clearfix"></div>
    </div>
</div>
    <div class="boxClasses">
    <div class="webContent">
        <ul class="listClasses">
                        <li>
                <a href="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-pa4lg2la1.html" class="">Group Fitness</a>
            </li>
                                        <li>
                <a href="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-cac-lop-hoc-pa4lg2la1ca1.html" class="">Các lớp học</a>
            </li>
                            <li>
                <a href="/CfycDesigner/template/cfycnew/try-a-class/group-fitness-dang-ky-hoc-thu-pa4lg2la1ca2.html" class="actived">Đăng ký học thử</a>
            </li>
                        </ul>
        <div class="clearfix"></div>
    </div>
</div>
                    <div class="mainWebsiteContent">
        <div class="webContent">