<?php
define('LANG_ABOUT_US_MAIN_TITLE', '<span>CALIFORNIA<br/>FITNESS & YOGA</span><br/>IN VIETNAM');
define('LANG_ABOUT_US_QUOTE','OUR GOAL IS TO SHOW PEOPLE THAT LIVING BETTER AND HEALTHIER IS NOT ABOUT DISCIPLINE AND SACRIFICE, BUT INSTEAD IS ABOUT INTEGRATING THOSE THINGS THAT ENHANCE YOUR LIFE AND ELIMINATING THE THINGS THAT DON’T.');

define('LANG_ABOUT_US_RANDY_QUOTE','The incredible success of California Fitness & Yoga can be linked to the vision and leadership of Founder and CEO, Randy G. Dobson. Randy brings to his company a passion for life and entertainment that is revolutionizing the way people exercise in Asia.');
define('LANG_ABOUT_US_PARAGRAPH1','In 2007, California Fitness & Yoga became the first and largest international fitness company to open in Vietnam. With a mission of “Making Life Better” California Fitness & Yoga is not just another ordinary gym. It’s a dynamic lifestyle center that aims to inspire, entertain and energize the communities it serves.</p>
                <p>California Fitness & Yoga is a place where fitness, fashion and entertainment merge in a healthy high energy environment. From the music and lighting to the state-of-the art equipment and world class instructors, every detail has been meticulously prepared to provide the greatest possible experience');
                
define('LANG_ABOUT_US_PARAGRAPH2', 'The members of CFYC’s  management group have  been key individuals on leadership teams for top fitness industry brands including 24 Hour Fitness, California Fitness, Jackie Chan Sport, UFC Gyms, Crunch Fitness, Yoga Works and Les Mills, just to name a few.</p>
                <p>With a management board that has over 30 years of combined experience in a dozen different countries, California Fitness & Yoga has one of the most well seasoned and professional leadership teams in the industry; enabling it to consistently deliver its brand promise to Make Life Better.');