<?php
define('LANG_ABOUT_US_MAIN_TITLE', '<span>CALIFORNIA<br/>FITNESS & YOGA</span><br/>IN VIETNAM');
define('LANG_ABOUT_US_QUOTE','CHÚNG TÔI MUỐN CHỨNG MINH RẰNG ĐỂ CÓ ĐƯƠC CUỘC SỐNG TỐT VÀ LÀNH MẠNH HƠN, BẠN KHÔNG NHẤT THIẾT PHẢI TUÂN THEO KỶ LUẬT THÉP HOẶC PHẢI HY SINH; THAY VÀO ĐÓ, CHỈ CẦN ĐƯA VÀO LỐI SỐNG CỦA MÌNH NHỮNG THÓI QUEN GIÚP NÂNG CAO CHẤT LƯỢNG CUỘC SỒNG, ĐỒNG THỜI GIẢM THIỂU NHỮNG THÓI QUEN KHÔNG CÓ LỢI..');

define('LANG_ABOUT_US_RANDY_QUOTE','The incredible success of California Fitness & Yoga can be linked to the vision and leadership of Founder and CEO, Randy G. Dobson. Randy brings to his company a passion for life and entertainment that is revolutionizing the way people exercise in Asia.');

define('LANG_ABOUT_US_PARAGRAPH1','Năm 2007 California Fitness & Yoga trở thành công ty thể dục thể hình quốc tế đầu tiên và lớn nhất ra mắt tại Việt Nam. Với sứ mệnh “Làm Cho Cuộc Sống Tốt Đẹp Hơn”, California Fitness & Yoga không chỉ đơn thuần giống như bao phòng tập thông thường khác. Đây là trung tâm của phong cách sống năng động, nhằm truyền cảm hứng, mang lại niềm vui sảng khoái cũng như nguồn sinh khí mới cho cộng đồng.</p>
<p>Đây là nơi hội tụ của việc luyện tập, thời trang và giải trí trong một môi trường lành mạnh, tràn trề sinh lực. Từ âm nhạc và ánh sáng cho tới các trang thiết bị hiện đại và đội ngũ huấn luyện viên đẳng cấp quốc tế, mỗi chi tiết đều được chuẩn bị một cách tỉ mỉ và công phu, nhằm mang lại những trải nghiệm tích cực và tuyệt vời nhất cho khách hàng.
Thành công vượt bậc của California Fitness & Yoga gắn liền với tầm nhìn và vai trò lãnh đạo của nhà sáng lập, đồng thời cũng là CEO – ông Randy G. Dobson. Randy đã thổi bùng trong toàn công ty của ông ngọn lửa đam mê tận hưởng cuộc sống và giải trí, vốn đã tạo nên một cuộc cách mạng trong cách luyện tập thể dục thể hình trên khắp châu Á.');
                
define('LANG_ABOUT_US_PARAGRAPH2', 'Các thành viên trong đội ngũ quản lý cấp cao của CFYC đều từng là những nhân vật cực kỳ quan trọng đối với sự phát triển của một số thương hiệu hàng đầu trong ngành thể dục thể hình, như: 24 Hour Fitness, California Fitness, Jackie Chan Sport, UFC Gyms, Crunch Fitness, Yoga Works và Les Mills. <br><br>

Với Hội đồng quản trị kết hợp của hơn 30 năm kinh nghiệm tại hàng chục quốc gia khác nhau, California Fitness & Yoga đã và đang sở hữu một đội ngũ lãnh đạo chuyên nghiệp và lão luyện bậc nhất trong ngành thể dục thể hình. Đó cũng là nguyên nhân chính giúp CFYC luôn trung thành và nhất quán trong việc thực hiện cam kết của thương hiệu: Làm Cho Cuộc Sống Tốt Đẹp Hơn.');