            <div class="space"></div>
            <div class="space"></div>
<div class="row footer-bar">
    <div class="col-xs-12">
        <a href="http://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fm.cfyc.com.vn%2F&p[title]=C%C3%A1c+Trung+t%C3%A2m+Th%E1%BB%83+D%E1%BB%A5c+Th%E1%BB%83+H%C3%ACnh+%26+Yoga+t%E1%BA%A1i+Vi%E1%BB%87t+Nam" title="Share">
            <span data-picture data-alt="icon share">
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-share.png"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-768/icon-share.png" data-media="(min-width: 481px)"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-1024/icon-share.png" data-media="(min-width: 769px)"></span>
                <noscript>
                    <img src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-share.png" alt="icon share">
                </noscript>
            </span>
        </a>
        <a href="http://m.cfyc.com.vn/desktop.php?url=%2F" title="Desktop version">
            <span data-picture data-alt="icon desktop">
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-desktop.png"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-768/icon-desktop.png" data-media="(min-width: 481px)"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-1024/icon-desktop.png" data-media="(min-width: 769px)"></span>
                <noscript>
                    <img src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-desktop.png" alt="icon desktop">
                </noscript>
            </span>
        </a>
        <a href="http://m.cfyc.com.vn/vn" title="Home">
            <span data-picture data-alt="icon home">
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-home.png"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-768/icon-home.png" data-media="(min-width: 481px)"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-1024/icon-home.png" data-media="(min-width: 769px)"></span>
                <noscript>
                    <img src="<?php echo $templateUrl ?>/images_server/images/responsive-480/icon-home.png" alt="icon home">
                </noscript>
            </span>
        </a>
    </div>
</div>
<div class="space"></div>
<div class="row footer text-center">
    <div class="col-xs-12">
        <p>Copyright © 2014 California Fitness & Yoga</p>
        <p>All rights reserved / Site by <a href="http://www.cfyc.com.vn/">www.cfyc.com.vn</a></p>
    </div>
</div>        </div>
    </div>
    <div id="progress"><div class="bar" style="width: 0%;"></div></div>
<div class="background-mask"></div>
<img src="<?php echo $templateUrl ?>/images_server/images/loading.gif" class="loading" alt="loading"/></body>
</html>