        <div class="box-bottom">
            <div class="webContent">
                <div class="navBottom">
                    <ul>
                        <li>
                            <a id="menuId_20" href="http://www.cfyc.com.vn/vn/career">Tuyển dụng</a>
                        </li>
                        <li>
                            <a id="menuId_21" href="http://www.cfyc.com.vn/vn/contact">Liên hệ</a>
                        </li>
                        <li>
                            <a id="menuId_22" href="http://www.cfyc.com.vn/vn/executive-team">Thông tin</a>
                        </li>
                        <li>
                            <a id="menuId_23" href="http://www.cfyc.com.vn/vn/gallery">Hình ảnh</a>
                        </li>
                        <li>
                            <a id="menuId_24" href="http://www.cfyc.com.vn/vn/terms-and-conditions">Điều kiện sử dụng</a>
                        </li>
                        <li>
                            <a id="menuId_25" href="http://www.cfyc.com.vn/vn/privacy-policy">Chính sách bảo mật</a>
                        </li>
                        <li>
                            <div class="tabSearch">
                                <form action="http://www.cfyc.com.vn/vn/search" method="post">
                                    <input type="text" class="txtSearch" name="txtKeyword" placeholder="Tìm kiếm">
                                    <input type="image" alt="Search" src="http://images.cfyc.com.vn/style/images/btnSearch.jpg" class="button-search" name="btSearch"></form>
                            </div>
                        </li>
                    </ul>
                    <div class="btnGotoTop">Lên đầu</div>
                </div>
                <div class="copyright">
                    <span>
                        Copyright &copy; 2012 <strong>California Fitness &amp; Yoga</strong>
                        / All rights reserved / Site by
                        <a href="http://www.cfyc.com.vn/"> <strong>www.cfyc.com.vn</strong>
                        </a>
                    </span>
                </div>
                <div class="iconSocial">
                    <a href="http://www.facebook.com/cfycvn" target="_blank" class="social6 no-border">
                        <span>&nbsp;</span>
                    </a>
                    <a href="https://plus.google.com/105335255808989803709/posts" target="_blank" class="social5">
                        <span>&nbsp;</span>
                    </a>
                    <a href="http://www.twitter.com/cfycvn" target="_blank" class="social2">
                        <span>&nbsp;</span>
                    </a>
                    <a href="http://www.youtube.com/user/califitnessyogavn" target="_blank" class="social3">
                        <span>&nbsp;</span>
                    </a>
                    <a href="http://www.centuryon.com" target="_blank" class="social4">
                        <span>&nbsp;</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>