<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <base href="/CfycDesigner/template/cfycnew/try-a-class/" target="_blank">
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" />
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Các Trung tâm Thể Dục Thể Hình & Yoga hàng đầu Việt Nam" />
    <meta name="keywords" content="Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam"/>
    <link rel="canonical" href="http://www.cfyc.com.vn/" />
    <title>Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam</title>
    <link href="http://images.cfyc.com.vn/phn_plugin/jquery-modal/jquery.modal.css?version=19" rel="stylesheet" type="text/css" media="screen" />
    <link href="http://images.cfyc.com.vn/phn_plugin/page/pace.min.css?version=19" rel="stylesheet" type="text/css" media="screen" />
    <link href="http://images.cfyc.com.vn/style/home.css?version=19" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_js/jquery.tools.min.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_js/jquery.nicescroll.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_js/jcarousellite_1.0.1.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_plugin/page/pace.min.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_js/jsPage.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_js/jquery.lazyload.min.js?version=19"></script>
    <script type="text/javascript" src="http://images.cfyc.com.vn/phn_plugin/jquery-modal/jquery.modal.min.js?version=19"></script>
</head>
<body>
    <div id="name-website">
        <div id="web-mainmenu">
            <div class="webContent">
                <div class="menuTab">
                    <div class="menuTopR">
                        <ul class="nav" id="nav1">
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/vn" id="menuId_13">
                                        <span>Trang chủ</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/cau-lac-bo-tai-ho-chi-minh-pa3lo1lg2.html" id="menuId_3">
                                        <span>Câu lạc bộ</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/gioi-thieu.html" id="menuId_6">
                                        <span>Về chúng tôi</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/group-fitness-pa4lg2la1.html" id="menuId_4">
                                        <span>Dịch vụ</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/nguoi-noi-tieng-tai-cali-pa5lg2ca11.html" id="menuId_5">
                                        <span>Phong cách sống</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/vn/member" id="menuId_7">
                                        <span>Thành viên</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="blockMenuTop">
                                    <a href="/vn/schedule" id="menuId_8">
                                        <span>Lịch học</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="logoTop">
                    <a href="http://www.cfyc.com.vn/vn">
                        <img src="http://images.cfyc.com.vn/style/images/LogoCalifornia.png" alt="LogoCalifornia.png" />
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>