<!DOCTYPE HTML>
<html lang="vn">
<head>
<meta charset=utf-8>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="description" content="Các Trung tâm Thể Dục Thể Hình & Yoga hàng đầu Việt Nam" />
<meta name="keywords" content="Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam"/>
<link rel="canonical" href="http://m.cfyc.com.vn/" />
<title>Các Trung tâm Thể Dục Thể Hình & Yoga tại Việt Nam</title>
<script>
    document.cookie    = 'resolution=' + Math.max(screen.width, screen.height) + '; path=/';
    BASE_URL           = 'http://m.cfyc.com.vn';
    CFYC_URL           = 'http://cfyc.com.vn';
    SIMS_URL           = 'https://sims.cfyc.com.vn';
    IMAGES_SERVER      = 'http://m.cfyc.com.vn/images_server';
    CFYC_IMAGES_SERVER = 'http://images.cfyc.com.vn';
</script>
<link rel="stylesheet" media="screen" href="http://m.cfyc.com.vn/images_server/css/bootstrap-3.1.1/css/bootstrap.min.css?version=12" />
<link rel="stylesheet" media="screen" href="http://m.cfyc.com.vn/images_server/fontello/css/fontello.css?version=12" />
<link rel="stylesheet" media="screen" href="http://m.cfyc.com.vn/images_server/css/default.css?version=12" />
</head>
<!-- always load picturefill firstly -->
<script src="<?php echo $templateUrl ?>/images_server/scripts/picturefill.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/picturefill.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/jquery/jquery-1.11.0.min.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/jquery/jquery.hammer-full.min.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/modernizr.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/css/bootstrap-3.1.1/js/bootstrap.min.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/common.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/showErrors.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/default.js?version=12"></script>
<script src="<?php echo $templateUrl ?>/images_server/scripts/default/index/index.js"></script>
</head>
<body>
    <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-KJ9WBZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KJ9WBZ');</script>
<!-- End Google Tag Manager -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '697911606960247']); })(); window._fbq = window._fbq || []; window._fbq.push(['track', 'PixelInitialized', {}]); </script> <noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=697911606960247&ev=NoScript" /></noscript>
<script type="text/javascript" class="microad_blade_track">
<!--
var microad_blade_gl = microad_blade_gl || { 'params' : new Array(), 'complete_map' : new Object() };
(function() {
var param = {'co_account_id' : '9308', 'group_id' : '', 'country_id' : '5', 'ver' : '2.1.0'};
microad_blade_gl.params.push(param);

var src = (location.protocol == 'https:')
? 'https://d-cache.microadinc.com/js/blade_track_gl.js' : 'http://d-cache.microadinc.com/js/blade_track_gl.js';

var bs = document.createElement('script');
bs.type = 'text/javascript'; bs.async = true;
bs.charset = 'utf-8'; bs.src = src;

var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(bs, s);
})();
-->
</script>
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '1490103637908386']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=1490103637908386&ev=PixelInitialized" /></noscript>
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '287423851465725']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=287423851465725&ev=PixelInitialized" /></noscript>
    <div class="container-fluid">
        <div class="canvas-navigation">
        <ul>
                <li class="active"><a class="parent" href="/vn">Trang chủ</a></li>
                        <li class=""><a class="parent" href="/cau-lac-bo-tai-ho-chi-minh-pa3lo1lg2.html">Câu lạc bộ</a></li>
                        <li class=""><a class="parent" href="/gioi-thieu.html">Về chúng tôi</a></li>
                        <li class=""><a class="parent" href="/group-fitness-pa4lg2la1.html">Dịch vụ</a></li>
                        <li class=""><a class="parent" href="/nguoi-noi-tieng-tai-cali-pa5lg2ca11.html">Phong cách sống</a></li>
                        <li class=""><a class="parent" href="/vn/member">Thành viên</a></li>
                        <li class=""><a class="parent" href="/vn/schedule">Lịch học</a></li>
                        <li class=""><a class="parent" href="http://m.cfyc.com.vn/vn/career">Tuyển dụng</a></li>
        <li class=""><a class="parent" href="http://m.cfyc.com.vn/vn/contact">Thông tin liên hệ</a></li>
                <li class=""><a class="parent" href="http://m.cfyc.com.vn/vn/executive-team">Thông tin</a></li>
                <li class=""><a class="parent" href="http://m.cfyc.com.vn/vn/gallery">Hình ảnh</a></li>
            </ul>
    </div>        <div class="outside">
            <div class="row">
    <div class="col-xs-12 text-center">
        <a href="http://m.cfyc.com.vn/vn">
            <span data-picture data-alt="Banner Centuryon 2">
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-480/logo-black.png"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-768/logo-black.png" data-media="(min-width: 481px)"></span>
                <span data-src="<?php echo $templateUrl ?>/images_server/images/responsive-1024/logo-black.png" data-media="(min-width: 769px)"></span>
                <noscript>
                    <img src="<?php echo $templateUrl ?>/images_server/images/responsive-480/logo-black.png" alt="Banner Centuryon 2">
                </noscript>
            </span>
        </a>
    </div>
</div><div class="space"></div>
<div class="row menu">
    <div class="col-xs-12">
        <div class="bar-social">
        <a href="<?php echo $linkChangeLanguage ?>">
        <img src="<?php echo $templateUrl ?>/images_server/images/vn.png" alt="vn.png"/>
    </a>
    <a href="http://www.facebook.com/cfycvn">
        <img src="<?php echo $templateUrl ?>/images_server/images/icon-facebook.png" alt="icon-facebook.png" />
    </a>
    <a href="https://plus.google.com/105335255808989803709/posts">
        <img src="<?php echo $templateUrl ?>/images_server/images/icon-google-plus.png" alt="icon-google-plus.png" />
    </a>
    <a href="http://www.twitter.com/cfycvn">
        <img src="<?php echo $templateUrl ?>/images_server/images/icon-tt.png" alt="icon-tt.png" />
    </a>
    <a href="http://www.youtube.com/user/califitnessyogavn">
        <img src="<?php echo $templateUrl ?>/images_server/images/icon-youtube.png" alt="icon-youtube.png" />
    </a>
    <a href="http://www.centuryon.com">
        <img src="<?php echo $templateUrl ?>/images_server/images/icon-centuryon.png" alt="icon-centuryon.png" />
    </a>
</div>        <div class="bar-setting">
    <div class="item">&nbsp;</div>
    <div class="item">&nbsp;</div>
    <div class="item">&nbsp;</div>
</div>    </div>
</div>
<div class="space"></div>